require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AlertKeywordsController do

  # This should return the minimal set of attributes required to create a valid
  # AlertKeyword. As you add validations to AlertKeyword, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "value" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AlertKeywordsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all alert_keywords as @alert_keywords" do
      alert_keyword = AlertKeyword.create! valid_attributes
      get :index, {}, valid_session
      assigns(:alert_keywords).should eq([alert_keyword])
    end
  end

  describe "GET show" do
    it "assigns the requested alert_keyword as @alert_keyword" do
      alert_keyword = AlertKeyword.create! valid_attributes
      get :show, {:id => alert_keyword.to_param}, valid_session
      assigns(:alert_keyword).should eq(alert_keyword)
    end
  end

  describe "GET new" do
    it "assigns a new alert_keyword as @alert_keyword" do
      get :new, {}, valid_session
      assigns(:alert_keyword).should be_a_new(AlertKeyword)
    end
  end

  describe "GET edit" do
    it "assigns the requested alert_keyword as @alert_keyword" do
      alert_keyword = AlertKeyword.create! valid_attributes
      get :edit, {:id => alert_keyword.to_param}, valid_session
      assigns(:alert_keyword).should eq(alert_keyword)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AlertKeyword" do
        expect {
          post :create, {:alert_keyword => valid_attributes}, valid_session
        }.to change(AlertKeyword, :count).by(1)
      end

      it "assigns a newly created alert_keyword as @alert_keyword" do
        post :create, {:alert_keyword => valid_attributes}, valid_session
        assigns(:alert_keyword).should be_a(AlertKeyword)
        assigns(:alert_keyword).should be_persisted
      end

      it "redirects to the created alert_keyword" do
        post :create, {:alert_keyword => valid_attributes}, valid_session
        response.should redirect_to(AlertKeyword.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved alert_keyword as @alert_keyword" do
        # Trigger the behavior that occurs when invalid params are submitted
        AlertKeyword.any_instance.stub(:save).and_return(false)
        post :create, {:alert_keyword => { "value" => "invalid value" }}, valid_session
        assigns(:alert_keyword).should be_a_new(AlertKeyword)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        AlertKeyword.any_instance.stub(:save).and_return(false)
        post :create, {:alert_keyword => { "value" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested alert_keyword" do
        alert_keyword = AlertKeyword.create! valid_attributes
        # Assuming there are no other alert_keywords in the database, this
        # specifies that the AlertKeyword created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        AlertKeyword.any_instance.should_receive(:update_attributes).with({ "value" => "MyString" })
        put :update, {:id => alert_keyword.to_param, :alert_keyword => { "value" => "MyString" }}, valid_session
      end

      it "assigns the requested alert_keyword as @alert_keyword" do
        alert_keyword = AlertKeyword.create! valid_attributes
        put :update, {:id => alert_keyword.to_param, :alert_keyword => valid_attributes}, valid_session
        assigns(:alert_keyword).should eq(alert_keyword)
      end

      it "redirects to the alert_keyword" do
        alert_keyword = AlertKeyword.create! valid_attributes
        put :update, {:id => alert_keyword.to_param, :alert_keyword => valid_attributes}, valid_session
        response.should redirect_to(alert_keyword)
      end
    end

    describe "with invalid params" do
      it "assigns the alert_keyword as @alert_keyword" do
        alert_keyword = AlertKeyword.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AlertKeyword.any_instance.stub(:save).and_return(false)
        put :update, {:id => alert_keyword.to_param, :alert_keyword => { "value" => "invalid value" }}, valid_session
        assigns(:alert_keyword).should eq(alert_keyword)
      end

      it "re-renders the 'edit' template" do
        alert_keyword = AlertKeyword.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AlertKeyword.any_instance.stub(:save).and_return(false)
        put :update, {:id => alert_keyword.to_param, :alert_keyword => { "value" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested alert_keyword" do
      alert_keyword = AlertKeyword.create! valid_attributes
      expect {
        delete :destroy, {:id => alert_keyword.to_param}, valid_session
      }.to change(AlertKeyword, :count).by(-1)
    end

    it "redirects to the alert_keywords list" do
      alert_keyword = AlertKeyword.create! valid_attributes
      delete :destroy, {:id => alert_keyword.to_param}, valid_session
      response.should redirect_to(alert_keywords_url)
    end
  end

end
